services:
  postgis:
    image: postgis/postgis:15-3.3-alpine
    environment:
      - POSTGRES_ROOT_PASSWORD=$POSTGRES_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgis_data: {}